import type { Prompt } from "../domain/types";
import type { PromptSource } from "../ports";

const duelPrompts: Prompt[] = [
  { id: "duel-01", text: "The worst slogan for a luxury air mattress:" },
  { id: "duel-02", text: "A warning label nobody expected to see on a birthday cake:" },
  { id: "duel-03", text: "The first sentence in a pirate’s performance review:" },
  { id: "duel-04", text: "A terrible name for a neighborhood watch group:" },
  { id: "duel-05", text: "The least reassuring thing a pilot can whisper:" },
  { id: "duel-06", text: "A rejected feature for the world’s fanciest refrigerator:" },
  { id: "duel-07", text: "The real reason the dinosaurs missed their meeting:" },
  { id: "duel-08", text: "A fortune cookie message that would ruin your evening:" },
  { id: "duel-09", text: "The worst possible phrase to put on matching family shirts:" },
  { id: "duel-10", text: "A line cut from a very honest dating profile:" },
  { id: "duel-11", text: "The title of a self-help book written by a raccoon:" },
  { id: "duel-12", text: "An unhelpful announcement at the world’s smallest airport:" },
  { id: "duel-13", text: "A suspicious new flavor of sparkling water:" },
  { id: "duel-14", text: "The worst thing to hear from your smart toaster:" },
  { id: "duel-15", text: "A museum exhibit that should not be interactive:" },
  { id: "duel-16", text: "A deeply unnecessary upgrade to the moon:" },
  { id: "duel-17", text: "The rejected mascot for a tax-preparation company:" },
  { id: "duel-18", text: "A terrible password hint for the nuclear launch codes:" },
  { id: "duel-19", text: "The name of a cruise ship you should absolutely avoid:" },
  { id: "duel-20", text: "A bold new rule for the public library:" },
  { id: "duel-21", text: "The one thing a ghost hates about open-plan offices:" },
  { id: "duel-22", text: "A rejected line from a motivational bathroom mirror:" },
  { id: "duel-23", text: "The worst theme for a restaurant’s escape room night:" },
  { id: "duel-24", text: "An excuse no time traveler should ever use:" },
  { id: "duel-25", text: "The tiny print on a coupon for one free dragon:" },
  { id: "duel-26", text: "Something you should never name a shared office printer:" },
  { id: "duel-27", text: "A sentence that makes a haunted house feel surprisingly affordable:" },
  { id: "duel-28", text: "The secret third option on every elevator:" },
  { id: "duel-29", text: "A very specific sign that your houseplant is judging you:" },
  { id: "duel-30", text: "The opening lyric of a song about doing laundry:" },
  { id: "duel-31", text: "A new Olympic event designed by house cats:" },
  { id: "duel-32", text: "What the detective found in the suspiciously dramatic lunchbox:" },
  { id: "duel-33", text: "The name of a candle scent for people who miss the office:" },
  { id: "duel-34", text: "A five-star review of a completely ordinary spoon:" },
  { id: "duel-35", text: "The only spell taught at budget wizard school:" },
  { id: "duel-36", text: "Something a dog would put on its résumé:" },
  { id: "duel-37", text: "The surprise item in a celebrity’s extremely boring gift bag:" },
  { id: "duel-38", text: "A new holiday tradition that lasts exactly eleven seconds:" },
  { id: "duel-39", text: "The password to the world’s most polite secret society:" },
  { id: "duel-40", text: "What a magician says when the trick is mostly paperwork:" },
  { id: "duel-41", text: "A headline from a newspaper run entirely by squirrels:" },
  { id: "duel-42", text: "The item that finally broke the grocery store self-checkout:" },
  { id: "duel-43", text: "A strangely competitive category at the county fair:" },
  { id: "duel-44", text: "The first complaint filed against a newly invented cloud:" },
  { id: "duel-45", text: "A pickup line used exclusively at aquarium sleepovers:" },
  { id: "duel-46", text: "The side effect of wearing socks designed by scientists:" },
  { id: "duel-47", text: "A new command you can teach a very advanced goldfish:" },
  { id: "duel-48", text: "What the villain forgot to include in the evil plan:" },
  { id: "duel-49", text: "The first rule of an extremely relaxed fight club:" },
  { id: "duel-50", text: "A question that gets you removed from a submarine tour:" },
  { id: "duel-51", text: "The slogan on a billboard visible only to birds:" },
  { id: "duel-52", text: "An oddly personal message from your microwave:" },
  { id: "duel-53", text: "The name of a podcast hosted by two medieval peasants:" },
  { id: "duel-54", text: "A reason the neighborhood parade is running six months late:" },
  { id: "duel-55", text: "The final boss in a video game about customer service:" },
  { id: "duel-56", text: "A compliment that sounds much worse through a megaphone:" },
  { id: "duel-57", text: "The first menu item at a restaurant on Mars:" },
  { id: "duel-58", text: "A suspicious thing for a scarecrow to keep in its pocket:" },
  { id: "duel-59", text: "The message inside a bottle that traveled three feet:" },
  { id: "duel-60", text: "A new feature nobody requested for the family group chat:" },
  { id: "duel-61", text: "The reason your future self only stayed for five minutes:" },
  { id: "duel-62", text: "A trophy awarded at the world’s quietest championship:" },
  { id: "duel-63", text: "The voice command that makes a smart home lose confidence:" },
  { id: "duel-64", text: "A note left on the fridge by a surprisingly organized ghost:" }
];

const finalePrompts: Prompt[] = [
  { id: "finale-01", text: "Write the first line of humanity’s group text with aliens:" },
  { id: "finale-02", text: "The one sentence that would make a genie quit on the spot:" },
  { id: "finale-03", text: "Write the final line of the world’s least inspiring movie:" },
  { id: "finale-04", text: "The announcement that instantly ends a royal wedding:" },
  { id: "finale-05", text: "A sentence guaranteed to make every robot in the room nervous:" },
  { id: "finale-06", text: "The first thing the moon says after becoming self-aware:" },
  { id: "finale-07", text: "The message humanity writes on the welcome mat for time travelers:" },
  { id: "finale-08", text: "The sentence that makes every superhero at the meeting leave:" },
  { id: "finale-09", text: "The first official announcement from the newly elected King of Pigeons:" },
  { id: "finale-10", text: "The final entry in Earth’s extremely honest travel brochure:" },
  { id: "finale-11", text: "What the universe whispers immediately after someone finds the meaning of life:" },
  { id: "finale-12", text: "The opening line of the apology letter sent by the future:" }
];

export const defaultPromptSource: PromptSource = {
  duelPrompts: () => duelPrompts.map((prompt) => ({ ...prompt })),
  finalePrompts: () => finalePrompts.map((prompt) => ({ ...prompt }))
};
